version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dtl-shop-be
    user: '${UID}:${GID}'
    restart: always
    env_file:
      - .env
    ports:
      - '8001:8000'
    networks:
      - dtl-shop
    volumes:
      - ./:/app/backend
      - /app/backend/node_modules
    expose:
      - 8001

networks:
  dtl-shop:
    driver: bridge
